/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Created:		May  6, 2023
 *			
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

#include "H5private.h"
H5_GCC_DIAG_OFF("larger-than=")

H5_CLANG_DIAG_OFF("overlength-strings")

char H5libhdf5_settings[]=
	"        SUMMARY OF THE HDF5 CONFIGURATION\n"
	"        =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.14.0\n"
	"                  Configured on: 2023-05-05\n"
	"                  Configured by: Visual Studio 16 2019\n"
	"                    Host system: Windows-10.0.19044\n"
	"              Uname information: Windows\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: C:/Program Files/HDF_Group/HDF5/1.14.0\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: \n"
	"              Debugging Symbols: OFF\n"
	"                        Asserts: OFF\n"
	"                      Profiling: OFF\n"
	"             Optimization Level: OFF\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: \n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS: /machine:x64\n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: shlwapi\n"
	"                       Archiver: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\n"
	"                         Ranlib: :\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: YES\n"
	"                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 19.29.30138.0\n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"                         CFLAGS:   /DWIN32 /D_WINDOWS -wd5105\n"
	"                      H5_CFLAGS: /W3;/wd4100;/wd4706;/wd4127\n"
	"                      AM_CFLAGS: \n"
	"               Shared C Library: YES\n"
	"               Static C Library: YES\n"
	"\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler:  \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: YES\n"
	"         Static Fortran Library: YES\n"
	"               Module Directory: N:/Development/Dev_Base/hdf5-1.14.0/msvc/mod\n"
	"\n"
	"                            C++: ON\n"
	"                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 19.29.30138.0\n"
	"                      C++ Flags:  /DWIN32 /D_WINDOWS /GR /EHsc /EHsc -wd5105\n"
	"                   H5 C++ Flags: /W3;/wd4100;/wd4706;/wd4127\n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: YES\n"
	"             Static C++ Library: YES\n"
	"\n"
	"                            JAVA: OFF\n"
	"                 JAVA Compiler:  \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                     Parallel HDF5: OFF\n"
	"  Parallel Filtered Dataset Writes: \n"
	"                Large Parallel I/O: \n"
	"                High-level library: ON\n"
	"Dimension scales w/ new references: \n"
	"                  Build HDF5 Tests: OFF\n"
	"                  Build HDF5 Tools: OFF\n"
	"                   Build GIF Tools: OFF\n"
	"                      Threadsafety: OFF\n"
	"               Default API mapping: v114\n"
	"    With deprecated public symbols: ON\n"
	"            I/O filters (external):  DEFLATE\n"
	"                        Direct VFD: \n"
	"                        Mirror VFD: \n"
	"                     Subfiling VFD: \n"
	"                (Read-Only) S3 VFD: \n"
	"              (Read-Only) HDFS VFD: \n"
	"    Packages w/ extra debug output: \n"
	"                       API Tracing: OFF\n"
	"              Using memory checker: OFF\n"
	"            Function Stack Tracing: OFF\n"
	"                  Use file locking: best-effort\n"
	"         Strict File Format Checks: OFF\n"
	"      Optimization Instrumentation: \n"
;

H5_GCC_DIAG_ON("larger-than=")
H5_CLANG_DIAG_OFF("overlength-strings")
